Resources:
  BusinessTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ByBlkBusinessTable-${self:custom.env}
      AttributeDefinitions:
        - AttributeName: slug
          AttributeType: S
        - AttributeName: csc # country_state_city
          AttributeType: S
        - AttributeName: region
          AttributeType: S
      KeySchema:
        - AttributeName: slug
          KeyType: HASH
        - AttributeName: csc
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: csc-index
          KeySchema:
            - AttributeName: region
              KeyType: HASH
            - AttributeName: csc
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ByBlkUserTable-${self:custom.env}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  InviteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ByBlkInviteTable-${self:custom.env}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: inviteCode
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      # GlobalSecondaryIndexes:
      #   - IndexName: inviteCode-index
      #     KeySchema:
      #       - AttributeName: inviteCode
      #         KeyType: HASH
      #     Projection:
      #       ProjectionType: ALL
